export const LOGIN_CONTACTNO = "LOGIN_CONTACTNO";
export const LOGIN_PASSWORD = "LOGIN_PASSWORD";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_INIT_LOGIN_LOADED = "LOGIN_INIT_LOGIN_LOADED";
export const LOGIN_RESET = "LOGIN_RESET";

export const REGISTER_COMPANYNAME = "REGISTER_COMPANYNAME";
export const REGISTER_CONTACTNO = "REGISTER_CONTACTNO";
export const REGISTER_PASSWORD = "REGISTER_PASSWORD";
export const REGISTER_CONFIRMPASSWORD = "REGISTER_CONFIRMPASSWORD";
export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_FINAL_SCREEN_LOADING = "REGISTER_FINAL_SCREEN_LOADING";
export const REGISTER_RESET = "REGISTER_RESET";

export const MOBILECONFIRMATION_CODE = "MOBILECONFIRMATION_CODE";
export const MOBILECONFIRMATION_LOADING = "MOBILECONFIRMATION_LOADING";
export const MOBILECONFIRMATION_BUTTON_DISABLED_TOGGLE = "MOBILECONFIRMATION_BUTTON_DISABLED_TOGGLE";
export const MOBILECONFIRMATION_RESET = "MOBILECONFIRMATION_RESET";

export const EMAILCONFIRMATION_CODE = "EMAILCONFIRMATION_CODE";
export const EMAILCONFIRMATION_LOADING = "EMAILCONFIRMATION_LOADING";
export const EMAILCONFIRMATION_BUTTON_DISABLED_TOGGLE = "EMAILCONFIRMATION_BUTTON_DISABLED_TOGGLE";
export const EMAILCONFIRMATION_RESET = "EMAILCONFIRMATION_RESET";

export const CHANGEPASSWORD_PASSWORD = "CHANGEPASSWORD_PASSWORD";
export const CHANGEPASSWORD_CONFIRMPASSWORD = "CHANGEPASSWORD_CONFIRMPASSWORD";
export const CHANGEPASSWORD_RESET = "CHANGEPASSWORD_RESET";
export const CHANGEPASSWORD_LOADING = "CHANGEPASSWORD_LOADING";

export const RESETPASSWORD_CONTACTNO = "RESETPASSWORD_CONTACTNO";
export const RESETPASSWORD_RESET = "RESETPASSWORD_RESET";
export const RESETPASSWORD_LOADING = "RESETPASSWORD_LOADING";

export const VENDOR_DRAWER_TOGGLE = "VENDOR_DRAWER_TOGGLE";

export const VENDOR_DRAWER_RESET = "VENDOR_DRAWER_RESET";

export const VENDOR_BOTTOM_DRAWER_TOGGLE = "VENDOR_BOTTOM_DRAWER_TOGGLE";
export const VENDOR_BOTTOM_DRAWER_INDEX = "VENDOR_BOTTOM_DRAWER_INDEX";
export const VENDOR_BOTTOM_DRAWER_RESET = "VENDOR_BOTTOM_DRAWER_RESET";

export const VENDOR_CHAT_BADGE = "VENDOR_CHAT_BADGE";
export const VENDOR_SEARCH_BADGE = "VENDOR_SEARCH_BADGE";
export const VENDOR_NOFICATIONS_BADGE = "VENDOR_NOFICATIONS_BADGE";
export const VENDOR_WELCOME_CALL_POP_UP_TOGGLE = "VENDOR_WELCOME_CALL_POP_UP_TOGGLE";
export const VENDOR_RESET = "VENDOR_RESET";

export const ADDEDITPRODUCT_IMAGES = "ADDEDITPRODUCT_IMAGES";
export const ADDEDITPRODUCT_ACTIVE_SLIDER_THUMBNAIL = "ADDEDITPRODUCT_ACTIVE_SLIDER_THUMBNAIL";
export const ADDEDITPRODUCT_CATEGORY_B = "ADDEDITPRODUCT_CATEGORY_B";
export const ADDEDITPRODUCT_CATEGORY_B_DATASET = "ADDEDITPRODUCT_CATEGORY_B_DATASET";
export const ADDEDITPRODUCT_CATEGORY_C = "ADDEDITPRODUCT_CATEGORY_C";
export const ADDEDITPRODUCT_CATEGORY_C_DATASET = "ADDEDITPRODUCT_CATEGORY_C_DATASET";
export const ADDEDITPRODUCT_PRODUCT_COLOR = "ADDEDITPRODUCT_PRODUCT_COLOR";
export const ADDEDITPRODUCT_TITLE = "ADDEDITPRODUCT_TITLE";
export const ADDEDITPRODUCT_PRICE = "ADDEDITPRODUCT_PRICE";
export const ADDEDITPRODUCT_DISCOUNT_MODAL_TOGGLE = "ADDEDITPRODUCT_DISCOUNT_MODAL_TOGGLE";
export const ADDEDITPRODUCT_DISCOUNT_QUANTITY = "ADDEDITPRODUCT_DISCOUNT_QUANTITY";
export const ADDEDITPRODUCT_DISCOUNT_PRICE = "ADDEDITPRODUCT_DISCOUNT_PRICE";
export const ADDEDITPRODUCT_DESCRIPTION = "ADDEDITPRODUCT_DESCRIPTION";
export const ADDEDITPRODUCT_LOADING = "ADDEDITPRODUCT_LOADING";
export const ADDEDITPRODUCT_LOADING_PERCENTAGE = "ADDEDITPRODUCT_LOADING_PERCENTAGE";
export const ADDEDITPRODUCT_CATEGORY_A_LOADING = "ADDEDITPRODUCT_CATEGORY_A_LOADING";
export const ADDEDITPRODUCT_CATEGORY_A_INPUT_VALUES = "ADDEDITPRODUCT_CATEGORY_A_INPUT_VALUES";
export const ADDEDITPRODUCT_CATEGORY_A_DATASET = "ADDEDITPRODUCT_CATEGORY_A_DATASET";

export const ADDEDITPRODUCT_RESET = "ADDEDITPRODUCT_RESET";

export const CONTACTUS_SUBJECT = "CONTACTUS_SUBJECT";
export const CONTACTUS_MESSAGE = "CONTACTUS_MESSAGE";
export const CONTACTUS_LOADING = "CONTACTUS_LOADING";
export const CONTACTUS_RESET = "CONTACTUS_RESET";

export const USERPROFILE_PROFILEAVATAR = "USERPROFILE_PROFILEAVATAR";
export const USERPROFILE_COMPANYNAME = "USERPROFILE_COMPANYNAME";
export const USERPROFILE_CONTACTNO = "USERPROFILE_CONTACTNO";
export const USERPROFILE_CONTACTNO_VERIFIED_NO = "USERPROFILE_CONTACTNO_VERIFIED_NO";
export const USERPROFILE_CONTACTNO_VERIFIED = "USERPROFILE_CONTACTNO_VERIFIED";
export const USERPROFILE_CONTACTNO_VERIFY_LOADING = "USERPROFILE_CONTACTNO_VERIFY_LOADING";
export const USERPROFILE_EMAIL = "USERPROFILE_EMAIL";
export const USERPROFILE_EMAIL_VERIFIED = "USERPROFILE_EMAIL_VERIFIED";
export const USERPROFILE_EMAIL_VERIFIED_EMAIL = "USERPROFILE_EMAIL_VERIFIED_EMAIL";
export const USERPROFILE_EMAIL_VERIFY_LOADING = "USERPROFILE_EMAIL_VERIFY_LOADING";
export const USERPROFILE_LOADING = "USERPROFILE_LOADING";
export const USERPROFILE_CONTENT_LOADING = "USERPROFILE_CONTENT_LOADING";
export const USERPROFILE_RESET = "USERPROFILE_RESET";


export const CUSTOMERQUERYFORM_COMPANYNAME = "CUSTOMERQUERYFORM_COMPANYNAME";
export const CUSTOMERQUERYFORM_BUYERNAME = "CUSTOMERQUERYFORM_BUYERNAME";
export const CUSTOMERQUERYFORM_LOCATION = "CUSTOMERQUERYFORM_LOCATION";
export const CUSTOMERQUERYFORM_CONTACTNO = "CUSTOMERQUERYFORM_CONTACTNO";
export const CUSTOMERQUERYFORM_SOURCEOFCONTACT = "CUSTOMERQUERYFORM_SOURCEOFCONTACT";
export const CUSTOMERQUERYFORM_SOURCEOFCONTACT_OTHERPLATFORM = "CUSTOMERQUERYFORM_SOURCEOFCONTACT_OTHERPLATFORM";
export const CUSTOMERQUERYFORM_ADDPRODUCTMODALTOGGLE = "CUSTOMERQUERYFORM_ADDPRODUCTMODALTOGGLE";
export const CUSTOMERQUERYFORM_ADDPRODUCTMODALSEARCH = "CUSTOMERQUERYFORM_ADDPRODUCTMODALSEARCH";
export const CUSTOMERQUERYFORM_PRODUCTDETAILSADDED = "CUSTOMERQUERYFORM_PRODUCTDETAILSADDED";
export const CUSTOMERQUERYFORM_PRODUCTDETAILSDATA = "CUSTOMERQUERYFORM_PRODUCTDETAILSDATA";
export const CUSTOMERQUERYFORM_STATUSOFQUERY = "CUSTOMERQUERYFORM_STATUSOFQUERY";
export const CUSTOMERQUERYFORM_ADDITIONALNOTE = "CUSTOMERQUERYFORM_ADDITIONALNOTE";
export const CUSTOMERQUERYFORM_LOADING = "CUSTOMERQUERYFORM_LOADING";
export const CUSTOMERQUERYFORM_RESET = "CUSTOMERQUERYFORM_RESET";

export const USER_AUTH_DATA = "USER_AUTH_DATA";
export const USER_AUTH_DATA_RESET = "USER_AUTH_DATA_RESET";


export const INFOFORPRODUCTSFORM_VALUECODEID = "INFOFORPRODUCTSFORM_VALUECODEID";
export const INFOFORPRODUCTSFORM_NAME = "INFOFORPRODUCTSFORM_NAME";
export const INFOFORPRODUCTSFORM_PRODUCTCATEGORY = "INFOFORPRODUCTSFORM_PRODUCTCATEGORY";
export const INFOFORPRODUCTSFORM_UOM = "INFOFORPRODUCTSFORM_UOM";
export const INFOFORPRODUCTSFORM_LENGTH = "INFOFORPRODUCTSFORM_LENGTH";
export const INFOFORPRODUCTSFORM_WIDTH = "INFOFORPRODUCTSFORM_WIDTH";
export const INFOFORPRODUCTSFORM_HEIGHT = "INFOFORPRODUCTSFORM_HEIGHT";
export const INFOFORPRODUCTSFORM_BRAND = "INFOFORPRODUCTSFORM_BRAND";
export const INFOFORPRODUCTSFORM_VENDOR = "INFOFORPRODUCTSFORM_VENDOR";
export const INFOFORPRODUCTSFORM_SUOM = "INFOFORPRODUCTSFORM_SUOM";
export const INFOFORPRODUCTSFORM_UNITS = "INFOFORPRODUCTSFORM_UNITS";
export const INFOFORPRODUCTSFORM_CASEWEIGHT = "INFOFORPRODUCTSFORM_CASEWEIGHT";
export const INFOFORPRODUCTSFORM_MANUFACTURERNAME = "INFOFORPRODUCTSFORM_MANUFACTURERNAME";
export const INFOFORPRODUCTSFORM_PRODUCTPRICE = "INFOFORPRODUCTSFORM_PRODUCTPRICE";
export const INFOFORPRODUCTSFORM_LOADING = "INFOFORPRODUCTSFORM_LOADING";
export const INFOFORPRODUCTSFORM_RESET = "INFOFORPRODUCTSFORM_RESET";

export const INTERNALSTANDARDSFORM_MANUFACTURERNAME = "INTERNALSTANDARDSFORM_MANUFACTURERNAME";
export const INTERNALSTANDARDSFORM_USERNAME = "INTERNALSTANDARDSFORM_USERNAME";
export const INTERNALSTANDARDSFORM_BUYERID = "INTERNALSTANDARDSFORM_BUYERID";
export const INTERNALSTANDARDSFORM_MANUFACTURERCOUNTRY = "INTERNALSTANDARDSFORM_MANUFACTURERCOUNTRY";
export const INTERNALSTANDARDSFORM_PORTOFLOADING = "INTERNALSTANDARDSFORM_PORTOFLOADING";
export const INTERNALSTANDARDSFORM_PAYMENTTERMS = "INTERNALSTANDARDSFORM_PAYMENTTERMS";
export const INTERNALSTANDARDSFORM_SHIPMENTTERMS = "INTERNALSTANDARDSFORM_SHIPMENTTERMS";
export const INTERNALSTANDARDSFORM_MODEOFSHIPMENT = "INTERNALSTANDARDSFORM_MODEOFSHIPMENT";
export const INTERNALSTANDARDSFORM_LOADING = "INTERNALSTANDARDSFORM_LOADING";
export const INTERNALSTANDARDSFORM_RESET = "INTERNALSTANDARDSFORM_RESET";

